export const masaArray = ['Catholic: Bucing Christian Upna tawh Kisai',
                          'Catholic: Azatna Athu tom',
                          'Pawlpi Kipatcil',
                          'Gamgi le Christian Upna Kido',
                          'Pasian Minam',
                          'Siadaw Ukgam (Diocese)',
                          'Siadaw Ukgam (2)',
                          'Siampi leh Nasep',
                          'Parish i cih in banghiam?',
                          'Thuzuite Kipawlna Tuamtuam',
                          'Pawlpi le Kipawlna']

export const nihnaArray = ['Upna Le Kammal/Thu (1)',
                           'Upna le Kammal (2)',
                           'Upna le Kammal (3)',
                           'Upna le Kammal (4)',
                           'Upna le Kammal (5)',
                           'Upna le Kammal (6)',
                           'Upna leh Ngeina',
                           'Ngeina leh Upna',
                           'Upna: Koi ah Kinga!',
                           'Upna in Mitmuhna ah Khuavak Hikhin Lo!',
                           'Picing Christian']

export const thumnaArray = ['Ama Aa Vive!',
                            'Khuazingsung Pasian Om',
                            'Upna Etkikna',
                            'Hahding kisam',
                            'Kua in Kei Hongsukha!',
                            'Jairus’ tanu',
                            'Penglam Christian!',
                            'Ze-et Hunciang',
                            'Pasian a Ittaktak Te',
                            'Ken Hongphawk Kha Lo!',
                            'Nadeihna Bang!',
                            'Nangdeihna Bang Hi Hen!',
                            'Hehnem Siampa Hehnepzia',
                            'Mary Magdalene leh Athokik Topa!',
                            'Nongsang Zodia?']

export const linaArray = ['Avanglian Tonu Maria',
                          'Mipa Minu masa le Mipa Minu nihna',
                          'Emmanuel: God is with us (Mt 1:18-24)',
                          'Khi Thungetna',
                          'Khi Thungetna le Alianbel Siampite',
                          'Nihgel Khenkei Ni',
                          "RC te'n LST Behlap cih Thu",
                          'Liausum Piakkul!',
                          'Asisa Kha te ading Nangbang Semthei?',
                          'Dahmahta leng Lungkim']

export const nganaArray = ['Papa Francis: Brazil Vaitun Thugenna',
                           'Piancil leh Tuhun Bangkilamdang',
                           'Caritas in Veritate Lungngaihna',
                           'Nahoihna Liimlangh in Mi',
                           'Mi in Mihing',
                           'Vengte!',
                           'Pawlpi Mite leh Pawlpi Honghilhna Thu',
                           'Azungkha Thu',
                           'Hun le Mun',
                           'Kalkaakden Kha ing',
                           'Zumlua ing!',
                           'Aw! Nang Piandang Mah Sicia!',
                           'Hell Kua Tung!',
                           'Thumgawm Khat',
                           'Lehluan',
                           'Phuukkhat',
                           'Umnuam mah ing Kacih Thu Pawlkhat',
                           'Lamdang Kasak Thu Pawlkhat',
                           'Ka ut lohpen Thu pawlkhat']
